### ISSUE TITLE
headphone jack not working

### ISSUE THREAD

**Issue by landon-holland** [tlefko/XPS13-9350-Catalina#14]
btw, this config is absolutely amazing.
the combo jack doesn't work for me, I've had it work before on other configs(? i don't really know what to call these) when i was on mojave and high sierra. when i plug in headphones, it shows that they are indeed connected and also the audio works fine with the builtin speakers.
![image](https://user-images.githubusercontent.com/16624272/81458965-5e6dbe00-916b-11ea-9ac6-f322be351019.png)

when i plug in my apple earbuds there is no sound, but for some reason when i plug in a pair of nicer headphones i can hear basically just a bunch of static on higher volumes that does actually match the media that i am listening to but it's just complete static.

thanks for helping!

**Comment by tlefko** [comment]
@landon-holland two suggestions, thank you so much by the way for your support means a lot :)

Try installing ccodec commander, also, you can try to use Voodoo just for the headphone jack -- I don't have any wired headphones but you can privately contact me and we can work thru this issue and I'll do my best to help

**Comment by landon-holland** [comment]
alright uh, i have no idea what those are so yeah i'm probably going to need some help lol. i'll at least try

**Comment by tlefko** [comment]
@landon-holland you can contact me on Instagram and I'll walk you through everything

**Comment by landon-holland** [comment]
landon.holland is my instagram

**Comment by tlefko** [comment]
Solved with disabling system gatekeeper and installing combojack
