### ISSUE TITLE
Trouble booting

### ISSUE THREAD

**Issue by Helicoss** [tlefko/XPS13-9350-Catalina#15]
Hello, I'm trying to get your EFI to work. I used to use syscl's distribution and recently decided to upgrade to Catalina. I've had nearly flawless success with the one provided by @Maz-1 (with a few minor tweaks to get it going), but my issue with it is that once the screen turns off, it refuses to turn back on, which is does not seem like a problem with your settings based on your readme.

Unfortunately, I'm running into a few issues, both with fresh install and with trying to boot up my existing installation that was made with @Maz-1's files. At first I was getting ApplePs2Controller: Notification consumer published, which can be resolved with adding SSDT-EC.aml. I was also wondering if there was a reason you didn't use EC in your SSDT or your config, how are you getting Catalina to boot without it?

Either way, I get much further after I've added SSDT-EC, but then I get stuck at IOconsoleUsers:GIOScreenLockState 3. I have not been able to figure out and have been stuck on this issue for a few days now. Is that an error you encountered? I'm using your config for HD520 as base.

I'm using an XPS 9350 with I7-6500u and HD520 iGPU, QHD+.
also using a 1 TB Intel 660p SSD and a DW1830 wifi card

Any help you can provide would be greatly appreciated!

**Comment by tlefko** [comment]
@Helicoss that is a weird issue -- do you mean with syscls upon waking up from sleep you can't get the display to turn back on? -- my EFI improves on this but it is not perfect, it is an issue that does occur with the QHD+ display. If you read my notes I detail this.

Contact me on Instagram if you would like to try to resolve the boot issue. I have identical specs and can just send you my personal EFI and we can figure out a solution together.

**Comment by tlefko** [comment]
@Helicoss that is a weird issue -- do you mean with syscls upon waking up from sleep you can't get the display to turn back on? -- my EFI improves on this but it is not perfect, it is an issue that does occur with the QHD+ display. If you read my notes I detail this I think but compared to other builds it is more reliable and will always after a couple lid wakes work.

However I think I know the problem. Do not sure HD520 config as a base. That is for testing.   remove  all the changes you made and just use the standard config.plist and let me know what happens? Should work :)

there won't be any EC issues don't worry they're addressed by remapping it in patches.

**Comment by Helicoss** [comment]
Thanks for the quick response! You were right, I used the default config this time. I had misunderstood the other config to apply if I had one of the indicated GPUs.

Everything works fine now, though as you mentioned the same screen issue exists for my model. I definitely noticed a few improvements, however. I'll mark this as closed.

**Comment by tlefko** [comment]
@Helicoss yeah it's a super annoying issue that I'm desperately trying to fix other than just disabling sleep altogether. Glad you noticed an improvement though!
