### ISSUE TITLE
Missing drive after installation

### ISSUE THREAD

**Issue by gctseng** [tlefko/XPS13-9350-Catalina#16]
I installed based on instructions, but after I copied over EFI folder, Clover boots without the drive.  I tried booting from the USB as well.  Basically, Clover can't see the drive.

The drivers are all there, but obviously there is an issue because the drive doesn't show up on the USB clover.

I used the latest EFI from the repository.  Let me know if anyone has any ideas.

BTW, I formatted using APFS.

**Comment by tlefko** [comment]
@gctseng please contact me at Tyler.lefko on instagram, I'll solve the issue with you and post full solution here

**Comment by tlefko** [comment]
but my guess is your drive is set to RAID in bios not achi -- just check that

**Comment by gctseng** [comment]
Was already set to ACHI.  I had reset the BIOS to default settings and then settings as suggested:
    Set all SATA operation as AHCI
    Disable Secure Boot, Fast Boot
    <DIDN'T DO THIS> For Coil Whine improvement disable C-States
    Enable UEFI Booting

**Comment by gctseng** [comment]
I believe the issue was that I turned on encryption (FileVault) because I ended up booting up the installed on the USB and Disk Utility was able to recognize the drive/volumes.  Instead of trying to work around it because I had not really done much, I just reinstalled.  Now I can see the drive in Clover.

I'll update if necessary in about a week or so.

**Comment by tlefko** [comment]
Any other issues? Or were you able to get everything setup @gctseng

**Comment by gctseng** [comment]
No other issues!

**Comment by tlefko** [comment]
Thank you for your feedback :)
