### ISSUE TITLE
Automatically Adjust Brightness not work

### ISSUE THREAD

**Issue by dhnvnm** [tlefko/XPS13-9350-Catalina#18]
I tried several Catalina guide for XPS 9350 included yours but no luck. Are there anything needed to tweak for specific laptop? Anyway, thank you for your hard work!

**Comment by tlefko** [comment]
@dhnvnm would you mind listing your specific model information?

as well as what bugs you experienced and how you installed macOS with this guide

**Comment by dhnvnm** [comment]
I think I figured it out. My laptop doesn't has the option Dynamic Backlight Control in the BIOS. Turn out I have to reinstall Windows and some driver from Dell to get that option. I will report back when it's done.

**Comment by tlefko** [comment]
> I think I figured it out. My laptop doesn't has the option Dynamic Backlight Control in the BIOS. Turn out I have to reinstall Windows and some driver from Dell to get that option. I will report back when it's done.

result?
