### ISSUE TITLE
Random flickering of QHD monitor

### ISSUE THREAD

**Issue by pjeorge** [tlefko/XPS13-9350-Catalina#20]
Hullo, I followed your guide. Everything works great. Thanks!
But I get random flickering from the built-in QHD monitor. I tried even with the guest accounts but it happens there as well.
What could I do to debug and improve the issue?

Thanks for your time

**Comment by pjeorge** [comment]
(I wasn't having this problem with Linux or with Windows on the same machine)
(I saw that there is a Beta version with Big Sur, but I'm more interested in a stable setup nowadays)

**Comment by tlefko** [comment]
@pjeorge what do you mean by random flickering? does this occur after sleep? -- I think this happens after a sleep sometimes because of the QHD screen. run this command and let me know the results.

sudo pmset -a sleep 0; sudo pmset -a hibernatemode 0; sudo pmset -a disablesleep 1;

the issue i think is random artifacting which you are describing which happens after wakeup

**Comment by pjeorge** [comment]
I actually already tried that but to no avail.
The screen basically turns completely off and on in less than a seconds.
It happens also from a fresh startup without sleep.

**Comment by tlefko** [comment]
@pjeorge add this into the plist config

-igfxmlr
-igfxonln=1 
igfxonln=1
igfxmlr

add all of those as separate arguments using clover configurator the config.plist 

use the - and without

**Comment by tlefko** [comment]
@pjeorge let me know if it helps

**Comment by pjeorge** [comment]
Had to revert cause I wasn't able to login in without external monitor. Still, thanks!
I'm going to try Big Sur EFI folder.

**Comment by pjeorge** [comment]
Nope. Still flikers after sleep disabled. When from shell mode gets detached and used standalone without external monitor 🤷

**Comment by tlefko** [comment]
have to be honest, never heard of this issue before. so unusual, im not
really sure whats ausing it

**Comment by pjeorge** [comment]
No worries. Thanks for the trouble
