### ISSUE TITLE
Touchpad not working 

### ISSUE THREAD

**Issue by x4080** [tlefko/XPS13-9350-Catalina#21]
Hi, @tlefko.

I already used your repo from Mojave, and not trying your Catalina repo. And I'm using 10.15.7 (from Mac OS installer - dosguy), everything went smoothly (after multiple reboots), but I have problem with touchpad (already copy the EFI Folder from GitHub to SSD's EFI) 

Touchpad not working at all, touch screen not working (while when booting installer works) - do you know how to fix it ?

Thanks

Edit : I'm using external keyboard and mouse and works great, and I'm from Mojave (not clean install) - just writing directly to Mojave installed Mac OS - maybe this is the problem ?

**Comment by x4080** [comment]
Solved it ! I just copied my old ACPI/Patched folder from my old Mojave EFI. And I use usb c hub, and works great to display to HDMI monitor, mouse and keyboard

Great job @tlefko

**Comment by tlefko** [comment]
@x4080 thank you so much man! I'm really glad it worked out for you. Hope you enjoy your machine my man :)

**Comment by x4080** [comment]
@tlefko Thanks, its all because of your kindness to share your hard work
