### ISSUE TITLE
Finder Tags not Working

### ISSUE THREAD

**Issue by Saad-LUMS** [tlefko/XPS13-9350-Catalina#4]
I add tags to files, click that tag in the sidebar but it shows up empty.

**Comment by tlefko** [comment]
@Saad-LUMS could it be a Catalina bug? I have no idea what hardware or driver issue could cause this

**Comment by Saad-LUMS** [comment]
I think it is related to Catalina. Worked fine in Mojave and should not be impacted by any driver.

**Comment by tlefko** [comment]
@Saad-LUMS I think once we patch the sleep lid issue we should have a really complete build, I think this issue could have to do with injecting a build ID. I saw a couple HDMI DP issuees online but that only applied to Catalina in this has been persistent. Thoughts?

**Comment by Saad-LUMS** [comment]
A restart seems to have solved the issue.

**Comment by tlefko** [comment]
:)
