### ISSUE TITLE
NVRAM - Brightness not persistent between reboots

### ISSUE THREAD

**Issue by ghost** [tlefko/XPS13-9350-Catalina#6]
After clearing up the NVRAM, making sure the EfiVariable is not in Clover, etc. I still have the issue of screen brightness going all the way up to 100% every time I reboot. Any thoughts?

**Comment by tlefko** [comment]
@manz4rk I will look into this, I think it's just the default display value to prevent the graphics from crashing on boot. Notice the intelgfxbcklight flag

**Comment by tlefko** [comment]
@manz4rk also just curious do you have sleep wake bug

**Comment by ghost** [comment]
Sleep wake bug as in...? Just tried sleeping and waking both on battery and AC and all looks good, the system wakes up when lifting the lid.

**Comment by tlefko** [comment]
@manz4rk that's so strange, mine actually has a bug when sleep wake is used. It does black screen with backlight on. What are your specifications. I'm glad it works tho

**Comment by ghost** [comment]
i5-6200U, 8GB, 1080p non-touch

**Comment by tlefko** [comment]
@manz4rk interesting, did installing kext fix camera?

**Comment by ghost** [comment]
> @manz4rk I will look into this, I think it's just the default display value to prevent the graphics from crashing on boot. Notice the intelgfxbcklight flag

Just to clarify - that was it! 
Flag `igfxcflbklt=1` is not really needed here, because it stands for CFL (Coffee Lake) backlight patch (9350 is on Skylake). Without it, brightness is properly saved in NVRAM.

**Comment by tlefko** [comment]
@manz4rk great! I'll patch this into the latest build --- might help with the backlight sleep bug too
