### ISSUE TITLE
10.15.4 Update Issue

### ISSUE THREAD

**Issue by Saad-LUMS** [tlefko/XPS13-9350-Catalina#7]
So, I was tempted to update. It rebooted to install the update and I chose "boot macOS install from Data"
![20200325_144100](https://user-images.githubusercontent.com/26320083/77573849-aa102500-6ea7-11ea-840d-5938bc8c74b9.jpg)

 and was met with something along the lines of CFG locked files. See output below. Any idea? 
![20200325_144121](https://user-images.githubusercontent.com/26320083/77573876-b5635080-6ea7-11ea-84bd-f670ea2f73e8.jpg)

I am still able to boot into my 10.15.3 partition and use it normally though, so it's all good.

**Comment by tlefko** [comment]
I'd recommend installing the updates from USBs, or into seperate partitions because it looks like it's trying to read the update file as commands in clover which is very very strange

**Comment by tlefko** [comment]
Wait for the official installer to come out that is full and then install it via usb. I think it will work fine actually @Saad-LUMS

**Comment by Saad-LUMS** [comment]
Cool. I'll just stick with 10.15.3 for a while and update to the final point release of Catalina when that comes to have some stability for a while since I'm daily driving it.

**Comment by ghost** [comment]
I'm on 10.15.4 right now with this config – be sure to update Clover to v5107 and everything should go smoothly.

**Comment by tlefko** [comment]
@manz4rk did you reinstall 10.15.3 before you did this to use my config? Just wondering if this my build or a combination of your previous files

**Comment by ghost** [comment]
I downloaded your config, updated the Clover and went straight to 10.15.4. Apart from the already resolved issues (Bluetooth, Webcam, Brightness) everything worked fine.

**Comment by tlefko** [comment]
@manz4rk thank you for that, any idea by the way what could cause the sleep wake black screen issue? You seem to know your stuff.

**Comment by ghost** [comment]
I think I had that problem back in Mojave or High Sierra... But honestly can't remember what solved it. Keeping Lilu and WhateverGreen updated, making sure hibernation is off and injecting the right graphics were always mentioned.

**Comment by tlefko** [comment]
@manz4rk shoot :(
