### ISSUE TITLE
Solution for Bluetooth

### ISSUE THREAD

**Issue by ghost** [tlefko/XPS13-9350-Catalina#8]
It might be different because i use DW1830 right now (still have DW1560 somewhere, but since it was not working years ago when I was doing Sierra/High Sierra hackintosh, I decided to change it), but the solution is to install 
```
BrcmBluetoothInjector.kext
BrcmFirmwareData.kext
BrcmPatchRAM3.kext
``` 
from https://github.com/acidanthera/BrcmPatchRAM to `EFI/Clover/Kexts/Other`.

**Comment by tlefko** [comment]
@manz4rk sure I'll try it, haven't even started looking into this, if it works I'll patch it into the build --- kinda preoccupied with the sleep wake issue atm

**Comment by tlefko** [comment]
@manz4rk I can't figure out how to download these files, would you mind sending a link to a downloads page

**Comment by ghost** [comment]
Just over the repo comments you have a bar with number of commits etc., find the releases and download from there. Here's a link to the page: https://github.com/acidanthera/BrcmPatchRAM/releases

**Comment by tlefko** [comment]
@manz4rk I tried to add those files but my bluetooth just spins and does not find an devices

**Comment by tlefko** [comment]
Bluetooth Patched via clover patches and additional kexts
