### ISSUE TITLE
Display Brightness Increase/Decrease with Charger Plugged in/out

### ISSUE THREAD

**Issue by Saad-LUMS** [tlefko/XPS13-9350-Catalina#9]
The brightness increases a noticeable bit when the charger is plugged in even though that power save setting is turned off (which makes an even more of a difference) but it should not.
Don't know if this is a MacOS thing or what.

<img width="780" alt="Screen Shot 2020-04-06 at 10 48 28 AM" src="https://user-images.githubusercontent.com/26320083/78571410-28e45680-77f4-11ea-8eac-76238c66cb09.png">

**Comment by tlefko** [comment]
@Saad-LUMS I’m not sure if it’s a bug, my Mac does it. Could be related to sleep wake with thunderbolt port though

**Comment by tlefko** [comment]
Patched in Beta release coming soon
